version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "6001:6001"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan reverb:serve
    ports:
      - "6001:6001"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
